// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_notes_id_delete from "./routes/api/notes/[id]/delete.ts";
import * as $api_notes_id_unlink from "./routes/api/notes/[id]/unlink.ts";
import * as $api_notes_create from "./routes/api/notes/create.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $notes_id_edit from "./routes/notes/[id]/edit.tsx";
import * as $notes_id_index from "./routes/notes/[id]/index.tsx";
import * as $notes_index from "./routes/notes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/notes/[id]/delete.ts": $api_notes_id_delete,
    "./routes/api/notes/[id]/unlink.ts": $api_notes_id_unlink,
    "./routes/api/notes/create.ts": $api_notes_create,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/notes/[id]/edit.tsx": $notes_id_edit,
    "./routes/notes/[id]/index.tsx": $notes_id_index,
    "./routes/notes/index.tsx": $notes_index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
